### ISSUE TITLE
Create proper Documentation of the  ML Models used.

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/DOCMED#4]
### ML MODELS
1. [COVID SYMPTOMS](https://github.com/jhabarsingh/DOCMED/blob/main/covid_symtoms/random_forest.py)
2. [XRAY PREDICTION](https://github.com/jhabarsingh/XRAY-COVID-PREDICTION/blob/master/corona_api/corona_static/xray_production.py)
3. [CT SCAN CLASSIFIER](https://github.com/jhabarsingh/DOCMED/blob/main/ct_scan/predit.py)
4. [CT SEGMENTATION](https://github.com/jhabarsingh/DOCMED/blob/main/ct_scan_segmentation/script.py)
5. [XRAY CLASSIFIER](https://github.com/jhabarsingh/DOCMED/blob/main/xray_classifier/script.py)

Add the Doc file in the [DOC](https://github.com/jhabarsingh/DOCMED/tree/main/docs) Folder

### DOC DETAILS

ML MODELS Doc Should Include

            1. Code Explanation (Brief)
            2. Input Format 
            3. Output Format
            4. What Model is Used?
            5. What all models were used?
            6. Why your choose the above Models?

**Comment by jhabarsingh** [comment]
Reply if you want to work on it.

**Comment by iam-aj** [comment]
Since we are moving towards evaluation,  I will be working on the ct_scan and covid_prediction models 
documentation.

**Comment by abhi9-akr** [comment]
Sure, Now we are at final stage So I will be working on the CT-Scan Segmentation, Covid-Symptoms and X-ray Prediction.

**Comment by iam-aj** [comment]
[ct_scan_predict.zip](https://github.com/jhabarsingh/DOCMED/files/6066461/ct_scan_predict.zip)
Documented CT_Scan Model
